\subsubsection*{From OpenCL to execution}
After the \gls{gamble} compiler have completed the output is OpenCL C code.
The OpenCL C code must be compiled by a C-compiler such as the GCC (GNU Compiler Collection) compiler to produce code the \acrshort{cpu} and \acrshort{gpu} can execute.
During the compilation the OpenCL C headers must be accessable, to provide the functions and types used. 
Aditionally the \gls{gamble} standard libary, containing functions such as \texttt{matrixToFile} and \texttt{fileToMatrix} must also be included and compiled. 
This produces an executable for the platform targetted by the compiler, this will most often be the platform running, such as x86-64 on Linux.
The same executeable is not usable for another platform, e.g. ARM, or on another operating system, e.g. Windows or OS X. 
However to maintain portability a ``MakeFile'' is used. 
A MakeFile is a file in the syntax which the make utility can execute. 
It is a set of rules which ensures that the correct compiler, path, headers, etc. are used during compilation on one of multiple platforms. 

This means that after running the \gls{gamble} compiler, on a configured computer, e.g. has OpenCL C headers, libary, a compiler etc. , the make command can be used to build a binary to execute.

The kernel isn't compiled at compiletime, but rather at runtime as this is where the unit to be executed upon is selected, this allows OpenCL to optimise for the specific unit the code is run upon, this is commonly known as JIT (Just in time) compilation, and online by OpenCL. \citep{openclbookjit}

A typical compilation under Ubuntu 14.04 configured with OpenCL headers located at \texttt{/opt/opencl-headers/include/} will look like \myref{lst:makecommands}, where \texttt{code.c} is the output of the \gls{gamble} compiler.
After the execution of these, an output file called \texttt{run} is made and can be executed with the command \texttt{./run}. 

\begin{lstlisting}[caption=The commands executed by the make command according to the rules of the MakeFile,numbers=none,frame=tlrb,label={lst:makecommands}]
gcc -Wall -Wextra -pedantic -O3 -std=c99 -I/opt/opencl-headers/include/ -c code.c simpleCL.c gambleStdlib.c
gcc -Wall -Wextra -pedantic -O3 -std=c99 *.o -o run -lm -lOpenCL -lrt
rm -f *.o
\end{lstlisting}